# Generated by Django 3.0.2 on 2020-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_auto_20200220_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.CharField(choices=[('pen', '等待审核'), ('pas', '通过'), ('rej', '未通过')], max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('is_male', models.BooleanField()),
                ('id_type', models.CharField(choices=[('idc', '身份证'), ('mil', '军官证'), ('pas', '护照'), ('hmt', '港澳台通行证'), ('chi', '儿童')], max_length=3)),
                ('id_number', models.CharField(max_length=18)),
                ('tel_number', models.CharField(max_length=11)),
                ('is_inhabitant', models.BooleanField()),
                ('area_type', models.CharField(choices=[('cit', '城市'), ('cou', '农村')], max_length=3)),
                ('district', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_wu_han', models.BooleanField()),
                ('is_wen_zhou', models.BooleanField()),
                ('is_hu_bei', models.BooleanField()),
                ('is_worker', models.BooleanField()),
                ('company_name', models.CharField(max_length=30)),
                ('is_stu', models.BooleanField()),
                ('school_name', models.CharField(max_length=30)),
                ('is_guest', models.BooleanField()),
                ('hotel_name', models.CharField(max_length=30)),
            ],
        ),
    ]
