# Generated by Django 3.0.2 on 2020-02-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_personinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='pending',
        ),
    ]
