# Generated by Django 3.0.2 on 2020-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_remove_personinfo_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='hotel_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='school_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
